version: "3.5"

services:
  api:
    container_name: auth-service_api
    build:
      context: .
      dockerfile: Dockerfile
    image: auth-service
    ports:
      - "8080:8080"
    depends_on: 
      - database
    networks:
      - auth-service-network
    restart: unless-stopped

  database:
    container_name: auth-service_database
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test123
      POSTGRES_DB: authdb
    volumes:
      - postgresql-volume:/var/lib/postgresql/data
    networks:
      - auth-service-network

networks:
  auth-service-network:
    name: noodlee-system-network
    driver: bridge
    
volumes:
  postgresql-volume:
